### ISSUE TITLE
Problem with the key when the button is 'Go to game start'

### ISSUE THREAD

**Issue by sdecandelario** [guar47/react-tutorial-tic-tac-toe#1]
When launching the app this message appears:

`Each child in an array or iterator should have a unique "key" prop.`

I think is because the value `stepNumber` isn't initialized in the Game constructor, and it's getting the null value. I think maybe can put this value at 0 in the constructor, right?

**Comment by KhairaF** [comment]
for me, I change the key to <li key={move}> and it will work.

**Comment by guar47** [comment]
Thanks for the issue! Fixed this.
